version: "3.7"

services:
  web:
    container_name: react_docker_exercise
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ".:/app"
