import React from "react";

import Head from "next/head";

const HomeComponent = (): JSX.Element => {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>NextApp</main>
    </React.Fragment>
  );
};

export default HomeComponent;
